### ISSUE TITLE
Plans for keeping up?

### ISSUE THREAD

**Issue by mjrudowsky** [javierjulio/jsoneditor-rails#3]
Wondering if there are any plans to keep this current with the jsoneditor project level? I just found both projects and was planning to use this gem for my Rails application, but it looks out of date.
Thanks!

**Comment by javierjulio** [comment]
@mjrudowsky thanks! Yes it just requires running a rake task to include the new assets. Its a manual process but I haven't had a need for it. It has been awhile so it would be good to get a release out. You'll find the rake task in the root Rakefile. If you open a PR with the changes I can cut a release for you.

**Comment by mjrudowsky** [comment]
Terrific! PR has been submitted to bring the project up to the 5.24.6 level of jsoneditor.

**Comment by javierjulio** [comment]
Closing this out due to #4
